### ISSUE TITLE
Add OG and Twitter card images

### ISSUE THREAD

**Issue by csbailey5t** [dickensnotes/ddnp#145]
Could go with logo, but @grenerad and @annamgibson will research and reflect.

**Comment by annamgibson** [comment]
Added twitterlogo image to images folder (not in a subfolder, but we can put it in one if need be). #180 /images/twitterlogo.jpg 

@csbailey5t Will the little Twitter preview pull description text directly from index.astro when we link to dickensnotes.com on twitter? Or do we need to create a custom "description" for this? If so, let's go with: "Exploring serial novel form with Charles Dickens's Working Notes."

**Comment by csbailey5t** [comment]
@annamgibson we'll explicitly set it, but we can re-use descriptions and such. Here's a good article that gives background on these: https://www.digitalocean.com/community/tutorials/how-to-add-twitter-card-and-open-graph-social-metadata-to-your-webpage-with-html

**Comment by csbailey5t** [comment]
@annamgibson I'll get this set up so with the `MainHead` component so adding this will be basically the same as adding the regular title and description metadata in the frontmatter of each page. 

Do you expect to have pages where the page title is different than the title you might want in the Twitter card? Same with the description.

**Comment by annamgibson** [comment]
I’ll have to check re the description (will do so today), but I can’t imagine we’d want different titles.

**Comment by csbailey5t** [comment]
Noting here that depending on which pages you want different cards, we'll need to specify the `og:type` per this ontology: https://ogp.me/#types

**Comment by csbailey5t** [comment]
@annamgibson we'll also need a non-logo, non-svg image file. Here's the description of what you want from Twitter's docs:

`A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.`

**Comment by annamgibson** [comment]
@csbailey5t  I imagine that most of the types will be "website"? 
I'll work on creating card images that fit the parameters you mentioned. We won't have them for every page, though. Will try to get this done by tmw and upload the images to the repository

**Comment by annamgibson** [comment]
Sent email with twitter card image options.

**Comment by annamgibson** [comment]
I've added the twitter card images to the repository (#196). I can fill in any metadata tags I need to once they're there. We'll need them for the following pages:

- [ ] Index (Home with logo.jpg)
- [ ] Scholarly Intro (IntroCard with logo.jpg)
- [ ] General Intro (IntroCard with logo.jpg)
- [ ] David Copperfield (DC card.jpg)
- [ ] Bleak House (BH card.jpg)

**Comment by csbailey5t** [comment]
Re-opening this to be addressed after domain switch.
