### ISSUE TITLE
Create team Vercel account for production hosting

### ISSUE THREAD

**Issue by csbailey5t** [dickensnotes/ddnp#168]

**Comment by dickensnotesadmin** [comment]
Anna here. I've created this admin account for access to Github and Vercel. I've created a Vercel account via this account. Account username is dickensnotesadmin and password is ddnp1870

**Comment by dickensnotesadmin** [comment]
@csbailey5t Let me know if I need to do anything else to set this up, but I think you should be able to log in with this account. 
@grenerad I've created an Important [Admin & Accounts do](https://docs.google.com/document/d/1IL2P1r_e3UYwS_OJxpLOP1DR2f4cW9ga7WAUbHlwcBo/edit?usp=sharing)c in the GDrive to centralize access to accounts like this.
