### ISSUE TITLE
pick icons for nav bar 

### ISSUE THREAD

**Issue by annamgibson** [dickensnotes/ddnp#171]
Go to fontawesome (solid, regular, light) and pick out icons for each item on the nav bar

**Comment by annamgibson** [comment]
https://docs.google.com/document/d/1oLM7wTXtDHHL2yZHvjcobBkGpy92q3XPu-1e1Tx-teA/edit?usp=sharing 
Waiting on Adam's review and will then create task list for Scott.

**Comment by annamgibson** [comment]
Scott, these icons are ready! I've listed the titles and codes, and I've put screen caps of each one there too. All are from the regular category, unless specified (there are two solids). https://docs.google.com/document/d/1oLM7wTXtDHHL2yZHvjcobBkGpy92q3XPu-1e1Tx-teA/edit?usp=sharing

**Comment by csbailey5t** [comment]
@annamgibson and @grenerad  I've got these in process. The regular icons you picked don't seem to be in the free version. I added everything I could from the solid icons. The other ones you'll need to find replacements for. 

Take a look at https://github.com/dickensnotes/ddnp/pull/192 for the current state and let me know what you want to do moving forward.
