### ISSUE TITLE
Refactor Mirador pages into layout

### ISSUE THREAD

**Issue by csbailey5t** [dickensnotes/ddnp#35]

**Comment by dnoneill** [comment]
@csbailey5t Not sure this is already in there, and didn't have the time to deep dive into Mirador  documentation to see if enabled, but I would like to have the ability to set the canvas to be a variable. i.e. https://main--tubular-narwhal-84b42b.netlify.app/notes/bleak-house/mirador/?canvas=https://dickensnotes.github.io/dickens-annotations/canvas/img/derivatives/iiif/bleakhousetranscriptions/BHWN18.json. Search isn't going to really work well without it. Here is how you can do so, you would have to check url variables. https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-how-do-i-programmatically-set-the-canvas

**Comment by csbailey5t** [comment]
@dnoneill I should be able to pre-render instances of Mirador with a specific canvas in view. It would quite be a query param, but more like `HOSTNAME/notes/bleak-house/mirador/canvas/BHWN18.json` or whatever we want as that last bit.

**Comment by dnoneill** [comment]
That works but Mirador and JS already have a built in way to do that without having to pre-render. Whichever works better for you. I just need the correct urls to feed into the script because right now they aren't right.
