### ISSUE TITLE
Create "How to Cite" banner at top for each page

### ISSUE THREAD

**Issue by grenerad** [dickensnotes/ddnp#67]
Ideally this will be smaller than the text size on the page itself--clearly visible but unobtrusive. We like how the Livingstone Online project does this: https://livingstoneonline.org/about-this-site/livingstone-online-introduction

**Comment by csbailey5t** [comment]
What should this citation be?

**Comment by grenerad** [comment]
They will be different for each page, but the one for the Editing the Notes page (for example) will read like this:

**How to cite this page (MLA):** Gibson, Anna, Frankie Goodenough, and Adam Grener. “Editing Dickens’s Working Notes.” _Digital Dickens Notes Project_. Anna Gibson and Adam Grener, dirs. 2022. Web. http://dickensnotes.com/about/editing-the-notes/

**Comment by annamgibson** [comment]
Citation text has been added to all pages except The Working Notes ones. Ready for styling with smaller text size and perhaps a separator as in the Livingstone Online example.
