### ISSUE TITLE
Set max-width for V&A images

### ISSUE THREAD

**Issue by csbailey5t** [dickensnotes/ddnp#72]
768px

**Comment by csbailey5t** [comment]
Max-width doesn't _seem_ to be an issue given constraints on width of the content column. Height, however, is a problem. This commit (5f99091844ca279360b60d46128132dabccc1601) constrains the max-height of an image that uses the `ImageWithCaption` component if passed `isVA={true}`. 

@grenerad or @annamgibson are there any instances of a V&A image that isn't in the central content column or that doesn't use the `ImageWithCaption` component?

**Comment by grenerad** [comment]
To my knowledge, all of the images we use from the V&A appear in the central content column with the ImageWithCaption component, so this constraint should ensure that all of those images conform to the permissions criteria.

**Comment by csbailey5t** [comment]
Fixed in https://github.com/dickensnotes/ddnp/commit/5f99091844ca279360b60d46128132dabccc1601
